from abc import ABC, abstractmethod

from hexagonal.domain.entities.post import Comment, Post
from hexagonal.domain.entities.social import Hashtag, Message, Notification, Story
from hexagonal.domain.entities.user import User


class AuthUseCasePort(ABC):
    @abstractmethod
    async def register(self, username: str, email: str, password: str, full_name: str | None) -> User: ...
    @abstractmethod
    async def login(self, email: str, password: str) -> str: ...
    @abstractmethod
    async def get_me(self, user_id: int) -> User: ...


class UserUseCasePort(ABC):
    @abstractmethod
    async def get_profile(self, user_id: int) -> dict: ...
    @abstractmethod
    async def update_me(self, user_id: int, **kwargs) -> User: ...
    @abstractmethod
    async def get_followers(self, user_id: int) -> list[User]: ...
    @abstractmethod
    async def get_following(self, user_id: int) -> list[User]: ...


class PostUseCasePort(ABC):
    @abstractmethod
    async def create(self, author_id: int, content: str | None, image_url: str | None) -> Post: ...
    @abstractmethod
    async def get(self, post_id: int) -> dict: ...
    @abstractmethod
    async def get_by_author(self, author_id: int, limit: int, offset: int) -> list[dict]: ...
    @abstractmethod
    async def delete(self, post_id: int, user_id: int) -> None: ...


class CommentUseCasePort(ABC):
    @abstractmethod
    async def create(self, post_id: int, author_id: int, content: str) -> Comment: ...
    @abstractmethod
    async def get_by_post(self, post_id: int, limit: int, offset: int) -> list[dict]: ...
    @abstractmethod
    async def delete(self, comment_id: int, user_id: int) -> None: ...


class LikeUseCasePort(ABC):
    @abstractmethod
    async def toggle(self, post_id: int, user_id: int) -> dict: ...


class FollowUseCasePort(ABC):
    @abstractmethod
    async def follow(self, follower_id: int, following_id: int) -> dict: ...
    @abstractmethod
    async def unfollow(self, follower_id: int, following_id: int) -> dict: ...


class FeedUseCasePort(ABC):
    @abstractmethod
    async def get_feed(self, user_id: int, limit: int, offset: int) -> list[dict]: ...


class StoryUseCasePort(ABC):
    @abstractmethod
    async def create(self, author_id: int, image_url: str | None, content: str | None) -> Story: ...
    @abstractmethod
    async def get_my_stories(self, user_id: int) -> list[Story]: ...
    @abstractmethod
    async def get_feed(self, user_id: int) -> list[Story]: ...
    @abstractmethod
    async def delete(self, story_id: int, user_id: int) -> None: ...


class MessageUseCasePort(ABC):
    @abstractmethod
    async def send(self, sender_id: int, receiver_id: int, content: str) -> Message: ...
    @abstractmethod
    async def get_conversations(self, user_id: int) -> list[dict]: ...
    @abstractmethod
    async def get_conversation(self, user_id: int, other_user_id: int, limit: int, offset: int) -> list[Message]: ...
    @abstractmethod
    async def mark_read(self, user_id: int, sender_id: int) -> dict: ...


class NotificationUseCasePort(ABC):
    @abstractmethod
    async def get_notifications(self, user_id: int, limit: int, offset: int) -> list[Notification]: ...
    @abstractmethod
    async def mark_read(self, notification_id: int, user_id: int) -> dict: ...
    @abstractmethod
    async def mark_all_read(self, user_id: int) -> dict: ...


class SearchUseCasePort(ABC):
    @abstractmethod
    async def search_users(self, query: str, limit: int) -> list[User]: ...
    @abstractmethod
    async def search_hashtags(self, query: str, limit: int) -> list[Hashtag]: ...
    @abstractmethod
    async def get_posts_by_hashtag(self, tag: str, limit: int, offset: int) -> list[dict]: ...
