from abc import ABC, abstractmethod

from clean.entities.post import Comment, Like, Post
from clean.entities.social import Follow, Hashtag, Message, Notification, Story
from clean.entities.user import User


class UserRepository(ABC):
    @abstractmethod
    async def create(self, user: User) -> User: ...
    @abstractmethod
    async def get_by_id(self, user_id: int) -> User | None: ...
    @abstractmethod
    async def get_by_email(self, email: str) -> User | None: ...
    @abstractmethod
    async def get_by_username(self, username: str) -> User | None: ...
    @abstractmethod
    async def update(self, user: User) -> User: ...
    @abstractmethod
    async def search(self, query: str, limit: int = 20) -> list[User]: ...


class PostRepository(ABC):
    @abstractmethod
    async def create(self, post: Post) -> Post: ...
    @abstractmethod
    async def get_by_id(self, post_id: int) -> Post | None: ...
    @abstractmethod
    async def get_by_author(self, author_id: int, limit: int, offset: int) -> list[Post]: ...
    @abstractmethod
    async def get_feed(self, following_ids: list[int], limit: int, offset: int) -> list[Post]: ...
    @abstractmethod
    async def delete(self, post_id: int) -> None: ...
    @abstractmethod
    async def count_by_author(self, author_id: int) -> int: ...


class CommentRepository(ABC):
    @abstractmethod
    async def create(self, comment: Comment) -> Comment: ...
    @abstractmethod
    async def get_by_id(self, comment_id: int) -> Comment | None: ...
    @abstractmethod
    async def get_by_post(self, post_id: int, limit: int, offset: int) -> list[Comment]: ...
    @abstractmethod
    async def delete(self, comment_id: int) -> None: ...


class LikeRepository(ABC):
    @abstractmethod
    async def create(self, like: Like) -> Like: ...
    @abstractmethod
    async def get(self, post_id: int, user_id: int) -> Like | None: ...
    @abstractmethod
    async def delete(self, post_id: int, user_id: int) -> None: ...
    @abstractmethod
    async def count_by_post(self, post_id: int) -> int: ...


class FollowRepository(ABC):
    @abstractmethod
    async def create(self, follow: Follow) -> Follow: ...
    @abstractmethod
    async def get(self, follower_id: int, following_id: int) -> Follow | None: ...
    @abstractmethod
    async def delete(self, follower_id: int, following_id: int) -> None: ...
    @abstractmethod
    async def get_followers(self, user_id: int) -> list[int]: ...
    @abstractmethod
    async def get_following(self, user_id: int) -> list[int]: ...
    @abstractmethod
    async def count_followers(self, user_id: int) -> int: ...
    @abstractmethod
    async def count_following(self, user_id: int) -> int: ...


class StoryRepository(ABC):
    @abstractmethod
    async def create(self, story: Story) -> Story: ...
    @abstractmethod
    async def get_by_id(self, story_id: int) -> Story | None: ...
    @abstractmethod
    async def get_active_by_author(self, author_id: int) -> list[Story]: ...
    @abstractmethod
    async def get_feed(self, following_ids: list[int]) -> list[Story]: ...
    @abstractmethod
    async def delete(self, story_id: int) -> None: ...


class MessageRepository(ABC):
    @abstractmethod
    async def create(self, message: Message) -> Message: ...
    @abstractmethod
    async def get_conversation(self, user_id: int, other_user_id: int, limit: int, offset: int) -> list[Message]: ...
    @abstractmethod
    async def get_conversations(self, user_id: int) -> list[dict]: ...
    @abstractmethod
    async def mark_as_read(self, user_id: int, sender_id: int) -> None: ...


class NotificationRepository(ABC):
    @abstractmethod
    async def create(self, notification: Notification) -> Notification: ...
    @abstractmethod
    async def get_by_user(self, user_id: int, limit: int, offset: int) -> list[Notification]: ...
    @abstractmethod
    async def mark_read(self, notification_id: int, user_id: int) -> None: ...
    @abstractmethod
    async def mark_all_read(self, user_id: int) -> None: ...


class HashtagRepository(ABC):
    @abstractmethod
    async def get_or_create(self, name: str) -> Hashtag: ...
    @abstractmethod
    async def link_post(self, post_id: int, hashtag_id: int) -> None: ...
    @abstractmethod
    async def unlink_post(self, post_id: int) -> None: ...
    @abstractmethod
    async def search(self, query: str, limit: int) -> list[Hashtag]: ...
    @abstractmethod
    async def get_posts_by_hashtag(self, tag: str, limit: int, offset: int) -> list[Post]: ...
