from abc import ABC, abstractmethod


class SecurityGateway(ABC):
    @abstractmethod
    def hash_password(self, password: str) -> str: ...
    @abstractmethod
    def verify_password(self, plain: str, hashed: str) -> bool: ...
    @abstractmethod
    def create_token(self, data: dict) -> str: ...
    @abstractmethod
    def decode_token(self, token: str) -> dict: ...
